name: push_nuget

# on manual click
on:
  workflow_dispatch:
    inputs:
      buildnumberMaj:
        description: 'Major Version'     
        required: true
        default: '0'
      buildnumber:
        description: 'Version'     
        required: true
        default: '1'                  
      buildnumberMin:
        description: 'Minor Version'     
        required: true
        default: '0'
      deploy:
          description: 'really push to nuget.org'
          required: false
          type: boolean

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: report version
      run: echo "${{ github.event.inputs.buildnumberMaj }}.${{ github.event.inputs.buildnumber }}.${{ github.event.inputs.buildnumberMin }}"

    - name: Git Checkout
      uses: actions/checkout@main

    - name: deploy
      if: ${{ github.event.inputs.deploy == 'true' }}
      run: echo "actually deploying..."

    - name: Setup Nuget.exe
      if: ${{ github.event.inputs.deploy == 'true' }}
      uses: nuget/setup-nuget@v2.0.0

    - name: Publish VL Nuget
      if: ${{ github.event.inputs.deploy == 'true' }}
      uses: vvvv/PublishVLNuget@1.0.43
      with:
        nuspec: deployment\VL.RichTextKit.nuspec
        version: ${{ github.event.inputs.buildnumberMaj }}.${{ github.event.inputs.buildnumber }}.${{ github.event.inputs.buildnumberMin }}
        
        icon-src: https://raw.githubusercontent.com/vvvv/PublicContent/master/nugeticon.png
        icon-dst: ./deployment/nugeticon.png
        
        nuget-key: ${{ secrets.NUGET_KEY }}